import {
  ArrowRight,
  WarningIcon,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  Info,
  Refresh,
  WifiOff,
  Watch,
  User,
  TrendingUp,
  TrendingDown,
  Trash,
  Unlock,
  ToggleLeft,
  ToggleRight,
  ThumbsUp,
  ThumbsDown,
  Thermometer,
  Tag,
  Shield,
  ShieldOff,
  Search,
  Settings,
  ShareExternal,
  ShareGraph,
  Connection,
  Plus,
  PlusCircle,
  Package,
  Piechart,
  Move,
  MoreHorizontal,
  MoreVertical,
  Expand,
  Minimize,
  MinusCircle,
  Maximize,
  MapPin,
  MessageCircle,
  Lock,
  LogOut,
  Mail,
  Loader,
  Layers,
  List,
  HelpCircle,
  Heart,
  Grid,
  Flag,
  Filter,
  Edit,
  Copy,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Barchart,
  Award,
  Calendar,
  Activity
} from './turbo-icons';

export const IconMapper = {
  'warning-octagon': WarningIcon,
  'arrow-right': ArrowRight,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  info: Info,
  refresh: Refresh,
  'wifi-off': WifiOff,
  watch: Watch,
  user: User,
  unlock: Unlock,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  trash: Trash,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  thermometer: Thermometer,
  tag: Tag,
  'shield-on': Shield,
  'shield-off': ShieldOff,
  'share-external': ShareExternal,
  'share-graph': ShareGraph,
  settings: Settings,
  search: Search,
  connection: Connection,
  plus: Plus,
  'plus-circle': PlusCircle,
  'pie-chart': Piechart,
  package: Package,
  move: Move,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  expand: Expand,
  minimize: Minimize,
  'minus-circle': MinusCircle,
  maximize: Maximize,
  'message-circle': MessageCircle,
  'map-pin': MapPin,
  mail: Mail,
  'log-out': LogOut,
  lock: Lock,
  loader: Loader,
  layers: Layers,
  list: List,
  'help-circle': HelpCircle,
  heart: Heart,
  grid: Grid,
  flag: Flag,
  filter: Filter,
  edit: Edit,
  copy: Copy,
  'chevrons-down': ChevronsDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up': ChevronsUp,
  'bar-chart': Barchart,
  calendar: Calendar,
  award: Award,
  activity: Activity
};
